# Changes here will be overwritten by Copier
_commit: v0.14.1
_src_path: gh:bhklab/bhklab-project-template
author_email: bhklab.katyscott@gmail.com
author_full_name: Katy Scott
github_username: strixy16
has_additional_authors: false
project_description: OCSCC Tumor Characterization applies MedSAM segmentation to an
    oral cavity squamous cell cancer patient cohort to explore how it affects treatment
    planning.
project_name: OCSCC Tumor Characterization
project_slug: ocscc-tumor-characterization
publish_to_github: true
python_version: '3.12'
repo_location: bhklab
